### ISSUE TITLE
Create parameter to set AllowEncodedSlashes in rucio.conf

### ISSUE THREAD

**Issue by ericvaandering** [rucio/containers#1]
This is a setting CMS needs

**Comment by tbeerman** [comment]
Sorry, took me a bit longer but I've now merged the PR and uploaded a new server image on docker hub.

**Comment by ericvaandering** [comment]
I'm not getting this as a plugin replacement. I see that 1.18.1 and 1.18.2 seem to be out of order on docker hub. Is that the issue?

**Comment by bari12** [comment]
1.18.2 was a client-only release, for that the docker container cannot be built.

**Comment by tbeerman** [comment]
Actually, the 1.18.2 client tag on Monday also triggered the server and daemons builds with this version number but since there is no pypi package the installed version in the container is still 1.18.1. We should delete those images directly afterwards. Also I did a manual build for the server two days ago including this patch and then uploaded it to docker hub. That's why they are out order.
